language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

before_install:
  - pip3 install --user adafruit-nrfutil
  - source $TRAVIS_BUILD_DIR/install.sh
script:
  - build_platform uno

notifications:
  email:
    on_success: change
    on_failure: change
